sudo: required
services:
  - docker
script:
  - docker build -t syedibtihaj/node .
  - docker images syedibtihaj/node
before_deploy:
  - docker login -u syedibtihaj -p "SYEDibtihaj12"
deploy:
  provider: script
  script: docker push syedibtihaj/node
  on:
    branch: master
